Kamj-2019/freemarket_sample_0622a

config/database.yml

WHAT
Unicornのインストールと設定を行う
WHY
config/database.ymlを修正したので、EC2インスタンスにプルする

Unicornの設定（修正）

---

config/unicorn.rb

WHAT
unicorn.rbのポート番号設定の変更。
WHY
Nginxを介した処理を行うためにunicornの設定変更を行う。

unicorn.rbのポート番号設定の変更

---

Gemfile
Gemfile.lock

WHAT
静的データ管理用及び進捗管理用Gemのインストール。
WHY
静的データを、テーブルではなくモデルファイルの中でhashとして定義・管理するために、Gemの「active_hash」を導入する。
また、商品の進捗を管理するためのGem「aasm」を導入する。

静的データ管理用及び進捗管理用Gemのインストール

---

Gemfile.lock
app/models/item.rb
db/migrate/20190713085641_create_items.rb
db/schema.rb
test/fixtures/items.yml
test/models/item_test.rb

Create Item table（without reference type)
アイテムテーブルの作成(リファレンス型以外のもの）
Items can be saved in DB and be created association with active hash 
アイテムをDBに保存する、またその後Activehashのアソシエーションを作成するため

Create table item

---

app/assets/stylesheets/devise/_login_footer.scss
app/assets/stylesheets/devise/_user_signin.scss

stylesheetの不具合を修正
stylesheetにaタグを記入したため、意図しない箇所にも反映されてしまったので修正を行う

stylesheetの不具合を修正

---

app/views/layouts/_header.html.haml

Update items Category in navi item
ナビ用のカテゴリーアイテムを更新 
Competed items category in navi list to see all 
ナビ用カテゴリーアイテムの表示を完成させるため

Update Category (navi-list)

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/mypage/_logout.scss
app/views/layouts/_sidebar.html.haml
app/views/users/logout.html.haml
config/routes.rb

ログアウト機能の実装
マイページからログアウトを可能にして、ユーザー管理の機能を充実させるため

ログアウト機能の実装

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/modules/_variable.scss
app/assets/stylesheets/mypage/_identification.scss
app/models/address.rb
app/models/prefecture.rb
app/views/users/edit.html.haml
db/migrate/20190809082943_create_addresses.rb
db/schema.rb
spec/models/address_spec.rb

Create user registration page
ユーザーの登録ページの作成
- User add new individual information
ユーザー情報を追加する
- Set prefecture form with Active-hash
ActiveHashを使用したフォームの実装

Create User Registration Page

---

app/assets/stylesheets/devise/_user_signin.scss
app/assets/stylesheets/devise/_user_signup.scss
app/views/items/index.html.haml
app/views/users/signup.html.haml
config/routes.rb

新規会員登録の分岐画面を作成
メールアドレス、facebook、googleで会員登録を可能にし、利便性を高めるために本ページでの分岐が必要

新規会員登録の分岐画面表示

---

app/controllers/items_controller.rb
app/controllers/users_controller.rb
config/routes.rb

WHAT
ルーティングおよびコントローラーの修正。
WHY
メンバー毎に個別に設定していたルートおよびアクションを整備するため。

ルーティングおよびコントローラーの修正

---

app/assets/stylesheets/users/_card.scss
app/views/users/card.html.haml

WHAT
「支払い方法」ページのコーディング
WHY
クレジットカード一覧の画面のみ作成。
クレジットカード登録画面は別段で作成する。

「支払い方法」ページのコーディング

---

app/assets/stylesheets/modules/_header.scss
app/views/layouts/_header.html.haml
app/views/layouts/_sidebar.html.haml

WHAT
ヘッダーとサイドバーのリンクの修正。
WHY
ヘッダーとサイドバーのリンクを修正し、各ページにアクセスできるようにする。

ヘッダーとサイドバーのリンクの修正

---

app/assets/stylesheets/modules/item_parts/_item-sell.scss
app/controllers/items_controller.rb
app/models/brand.rb
app/models/delivery_fee_payer.rb
app/models/delivery_method.rb
app/models/evaluation.rb
app/models/first_category.rb
app/models/prefecture.rb
app/models/shipping_day.rb
app/models/size.rb
app/models/status.rb
app/views/items/index.html.haml
app/views/items/new.html.haml

商品出品ページの作成
（item関連のview、controller、CSSの編集およびそれに伴う微修正）
開発アプリ必須機能のため

Make item exhibit page1

---

app/assets/stylesheets/modules/item_parts/_item-detail.scss
app/views/items/show.html.haml

WHAT
商品詳細ページの修正。
WHY
商品購入確認ページへのリンクボタンを修正するため。

商品詳細ページの修正

---

config/routes.rb

WHAT
routes.rbを修正する。
WHY
ユーザープロフィールページのルートを修正するため。

routes.rbの修正

---

app/controllers/cards_controller.rb
app/models/card.rb
db/migrate/20190902124317_create_cards.rb
db/schema.rb
spec/controllers/cards_controller_spec.rb
spec/helpers/cards_helper_spec.rb
spec/models/card_spec.rb

Cards tableとCards controllerの作成
Pay.jp機能の実装にあたって、関連テーブルとコントローラの作成を行う

Cards Tableの作成

---

Gemfile
Gemfile.lock
app/controllers/users/confirmations_controller.rb
app/controllers/users/omniauth_callbacks_controller.rb
app/controllers/users/passwords_controller.rb
app/controllers/users/registrations_controller.rb
app/controllers/users/sessions_controller.rb
app/controllers/users/unlocks_controller.rb
app/views/devise/sessions/new.html.haml
app/views/signup/card.html.haml
app/views/signup/personal.html.haml

reCAPTCHAの実装
reCAPTCHAを実装することで悪質なアクセスを防ぐため

reCAPTCHAの実装

---

app/assets/stylesheets/modules/item_parts/_categorypage.scss
app/views/items/category.html.haml

WHAT
カテゴリーからの商品一覧ページの作成。
WHY
カテゴリーを絞っての一覧を表示させるため。

カテゴリーからの商品一覧ページの作成

---

app/assets/stylesheets/modules/item_parts/_brandpage.scss
app/views/items/brand.html.haml

WHAT
ブランド名からの商品一覧ページの作成。
WHY
ブランド名を絞っての一覧を表示させるため。

ブランド名からの商品一覧ページの作成

---

app/assets/stylesheets/modules/item_parts/_item-sell.scss
app/views/items/new.html.haml

プロダウンボックスの見た目に崩れが生じていたので補正しました。
見た目修正のため。

minor change

---

app/views/items/category.html.haml

WHAT
カテゴリー一覧ページの修正
WHY
商品を降順表示にするため。

カテゴリー一覧ページの修正

---

app/assets/stylesheets/modules/_notification.scss
app/assets/stylesheets/signup/_progress.scss
app/assets/stylesheets/transaction/home.scss
app/controllers/transactions_controller.rb
app/views/items/show.html.haml
app/views/transactions/_notification.html.haml
app/views/transactions/done.html.haml
app/views/transactions/show.html.haml
config/routes.rb

Create transaction (buy) action and view
購入画面の実装
#why
User can buy the item
ユーザーが商品の購入を行える

Create transaction action/商品購入の実装

---

app/controllers/transactions_controller.rb
app/views/users/show.html.haml

transaction_contollerおよび、show.html.hamlの一部修正
nicknameを表示させる

Miner change/微細修正

---

config/deploy.rb

WHAT
deploy.rbを修正する。
WHY
デプロイ時に、deploy.rbの環境変数のセット（set :default_env{}）に、payjpとreCAPTCHAを追加するため。

deploy.rbの修正

---

config/secrets.yml

WHAT
secrets.ymlを修正する。
WHY
環境変数を追加するため。

secrets.ymlの修正

---

app/models/item_image.rb
config/initializers/carrierwave.rb

WHAT
carrierwave.rbを修正する。
WHY
本番環境での画像保存ということを明確にするため下記の条件文を追記。
if Rails.env.production?
end

carrierwave.rbの修正

---

app/controllers/items_controller.rb
app/models/item.rb

WHAT
items_controller.rbおよびitem.rbの修正
WHAY
items_controller.rbにて商品情報の降順取得の記述を簡略化するため。
item.rbのActivehashを使用する記述の記述個所の変更をするため。

items_controller.rbおよびitem.rbの修正

---

app/views/transactions/show.html.haml

WHAT
show.html.hamlを修正する。
WHY
未設定ページへのリンクを外すため。

show.html.hamlを修正する
