Capfile, Gemfile, Gemfile.lock, config/deploy.rb, config/deploy/production.rb, config/deploy/staging.rb, config/environments/production.rb, config/unicorn.rb
WHAT
自動デプロイツールCapistranoを導入する。
WHY
手動でデプロイを行うことの煩雑さを解消するため、コマンド一つで自動でデプロイ出来るようにするため。
=> Capistranoの導入

config/deploy.rb
WHAT
自動デプロイツールCapistranoを導入する。
WHY
シンタックスエラーが出たため、その修正を行った。
=> Capistranoの導入（修正）

app/models/item.rb
WHAT
WHY
"NoMethodError: undefined method `has_many' for Brand:Class"
自動デプロイで上記エラーが出る原因がアソシエーションの記述の仕方（belongs_to_active_hash :brand）ではないかと仮定し、item.rbに下記の一文を記述し、確認するため。
extend ActiveHash::Associations::ActiveRecordExtensions
=> 自動デプロイのエラー原因を探るための切り分け(item.rb)

app/models/item.rb
WHAT
WHY
"NoMethodError: undefined method `has_many' for Brand:Class"
自動デプロイで上記エラーが出る原因がアソシエーションの記述の仕方ではないかと仮定し、
belongs_to_active_hash　→　belongs_to
と記述を変更し、確認するため。
=> 自動デプロイのエラー原因を探るための切り分け２(item.rb)

app/models/item.rb
WHAT
WHY
"NoMethodError: undefined method `has_many' for Brand:Class"
自動デプロイで上記エラーが出る原因がアソシエーションの記述の仕方ではないかと仮定し、
belongs_to :brand　→　belongs_to :brand, optional: true
と記述を変更し、確認するため。
=> 自動デプロイのエラー原因を探るための切り分け3(item.rb) 

app/models/brand.rb
WHAT
WHY
ActiveHashファイル「brand.rb」の記述の仕方を、
field :brand
create id: 1, brand: 'アーヴェヴェ'
↓
self.data = [
{id: 1, brand: 'アーヴェヴェ'},
に変更した。
=> 自動デプロイのエラー原因を探るための切り分け４(item.rb)

app/models/delivery_fee_payer.rb
WHAT
WHY
"NoMethodError: undefined method `has_many' for DeliveryFeePayer:Class"
自動デプロイで上記エラーが出る原因がアロー記法ではないことが原因ではないかと仮定し、下記のように変更し検証するため。
create id: 1, delivery_fee_payer: '送料込み(出品者負担)'
↓↓↓
create :id => 1, :delivery_fee_payer => '送料込み(出品者負担)'
=> 自動デプロイのエラー原因を探るための切り分け(delivery_fee_payer.rb)

app/models/delivery_fee_payer.rb, app/models/item.rb
WHAT
WHY
"NoMethodError: undefined method `has_many' for DeliveryFeePayer:Class"
自動デプロイで上記エラーが出る原因が、下記記述がないことが原因ではないかと仮定し、検証するため。
include ActiveHash::Associations
=> 自動デプロイのエラー原因を探るための切り分け２(delivery_fee_payer.rb) 

app/models/delivery_fee_payer.rb, app/models/item.rb
WHAT
WHY
"NoMethodError: undefined method `has_many' for DeliveryFeePayer:Class"
自動デプロイで上記エラーが出る原因が、`has_many'の記述がある事が原因ではないかと思い、検証するため。
=> 自動デプロイのエラー原因を探るための切り分け３(delivery_fee_payer.rb) 

app/models/category.rb, app/models/delivery_method.rb, app/models/evaluation.rb, app/models/first_category.rb, app/models/second_category.rb, app/models/shipping_day.rb, app/models/size.rb, app/models/sizes_category.rb, app/models/status.rb, app/models/third_category.rb, app/models/user_detail.rb, app/models/users_evaluation.rb, db/schema.rb
WHAT
自動デプロイのエラー原因となるActiveHashのアソシエーションの修正。
WHY
"NoMethodError: undefined method has_many' for DeliveryFeePayer:Class" 
検証の結果、自動デプロイで上記エラーが出る原因が、'has_many'の記述がある事と判明したため、ActiveHashファイルを修正するため。
=> ActiveHashのアソシエーションの修正

Gemfile.lock
WHAT
脆弱性対応のためのGemのアップデート。
WHY
Gem(nokogiri)に対してセキュリティーアラートが出ていたのでアップデートを行う。
=> 脆弱性対応のためのGemのアップデート

db/migrate/20190825062201_change_column_to_allow_null.rb
WHAT
itemsテーブルのカラムのNOT NULL制約の変更。
WHY
サイズやブランドのない商品を出品する際に、値がnullでも登録できるようにするため、itemsカラムのsize_id及びbrand_idを「null: true」に変更する。
=> itemsテーブルのカラムのNOT NULL制約の変更

db/schema.rb
WHAT
itemsテーブルのカラムのNOT NULL制約の変更。
WHY
migrationファイルのみpushしてしまい、schema.rbをpushし忘れたため。
=> itemsテーブルのカラムのNOT NULL制約の変更（２）

app/models/item.rb, db/migrate/20190831092322_add_aasm_state_to_items.rb, db/schema.rb
WHAT
商品の状態遷移をaasmで管理する。
WHY
商品の出品状態の遷移を制御する為に、models/items.rbに状態・イベント・遷移を定義し、itemsテーブルに状態管理用のカラムを追加するため。
=> 商品の状態遷移をaasmで管理する

app/controllers/items_controller.rb, app/models/item.rb, app/views/items/new.html.haml
item出品ページの作成。
（itemsテーブルの情報は保存できる状態だったので、fields_forを用いたitem_imageへのimage_urlの保存を実装しました）
サービス設計上必要なため
=> make item exhibit page

app/views/users/profile.html.haml
WHAT
プロフィールページを修正。
WHY
商品出品のリンク先を設定するため。
=> プロフィールページの修正

app/models/item_image.rb
WHAT
item_image.rbを修正する。
WHY
画像が非表示になる不具合を修正するため。
=> item_image.rbの修正

app/assets/stylesheets/modules/item_parts/_item-detail.scss, app/controllers/items_controller.rb, app/models/item.rb, app/views/items/destroy.html.haml, app/views/items/show.html.haml
商品削除機能の実装。
・item.rb
→外部キーを持つテーブルのdestroyアクションを動かすためのコード記載。
・items_controller.rb
→item出品者とログインユーザーが同じ場合にdestroyアクションを動かすことができるためのコントローラー設定。
・destroy.html.haml
→商品削除した後の遷移ページ（削除確認）の作成。
・show.html.haml
→ログインユーザーと商品出品者が同じ場合に商品削除ボタンが表示され、異なる場合に商品購入ボタンが表示されるようにコードを記載、それに伴いクラス名も微修正しています。（念のためコメントアウトで元のコードを残しています。）
・_item-detail.scss
→show.html.hamlの変更に伴うコードの微修正を加えています。
必須機能のため。
=> Make destroy function

app/controllers/transactions_controller.rb, app/views/items/index.html.haml
WHAT
商品状態遷移の修正およびトップページリンク修正。
WHY
商品状態遷移のエラー修正のためtransactions_controller.rbを修正し、トップページのリンクの修正を行うため。
=> 商品状態遷移の修正およびトップページリンク修正

app/assets/stylesheets/transaction/home.scss, app/controllers/transactions_controller.rb, app/views/transactions/done.html.haml, app/views/transactions/show.html.haml
WHAT
購入画面非表示の修正。
WHY
購入画面が表示できない状況の解消および購入画面にクレジットカード情報を表示させるため。
=> 購入画面非表示の修正

app/views/items/show.html.haml
WHAT
商品詳細ページのリンクの修正。
WHY
商品詳細ページのlink_toに、method: :getを明記するため。
=> 商品詳細ページのリンクの修正

app/controllers/cards_controller.rb, config/routes.rb
WHAT
routes.rbを修正。
WHY
production.logに「No route matches {:action=>"new", :controller=>"card", :id=>"100"}」と記載があったため、不必要なルートを削除するため。
=> routes.rbの修正

app/controllers/transactions_controller.rb
WHAT
transactions_controller.rbの修正。
WHY
showアクションのif @card.blank?条件の際のリダイレクト先コントローラー名を"cards"と複数形にするため
。
=> transactions_controller.rbの修正
